# Generated by Django 2.0.3 on 2018-04-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=30, verbose_name='Clave del producto o servicio')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('amount', models.CharField(max_length=16, verbose_name='Monto de Factura')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expedition', models.DateTimeField(verbose_name='Fecha de expedicion')),
                ('moneda', models.CharField(max_length=4)),
                ('folio', models.CharField(max_length=20)),
                ('way_to_pay', models.CharField(max_length=30, verbose_name='Forma de Pago')),
                ('concepts', models.ManyToManyField(blank=True, to='facturas.Concept', verbose_name='Comceptos')),
            ],
        ),
    ]
