# Generated by Django 2.0.3 on 2018-04-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=30, verbose_name='Clave del producto o servicio')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('amount', models.CharField(max_length=16, verbose_name='Monto de Factura')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('date_expedition', models.DateTimeField(verbose_name='Fecha de expedicion')),
                ('coin', models.CharField(max_length=4)),
                ('folio', models.CharField(max_length=20)),
                ('way_to_pay', models.CharField(max_length=30, verbose_name='Forma de Pago')),
                ('concepts', models.ManyToManyField(blank=True, to='facturas.Concept', verbose_name='Comceptos')),
                ('emisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
        ),
    ]
