# Generated by Django 2.0.3 on 2018-04-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_auto_20180415_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='moneda',
            new_name='coin',
        ),
    ]
