# Generated by Django 2.0.3 on 2018-04-16 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20180416_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
