# Generated by Django 2.0.3 on 2018-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180415_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='Razon Social'),
        ),
    ]
